### ISSUE TITLE
"The configured gift could not be found."

### ISSUE THREAD

**Issue by gino2014** [witrin/magento-gifts#29]
A sale has been stopped and by taking a look at the customers at "Customers- Manage Customers" 
i got only this error "There has been an error processing your request-Exception printing is disabled by default for security reasons." 
We are using Magento 1.9.0.1 with all patches till Oct 3, 2014. Maybe someone has a solution. Thanks in advance.
At the error log file i got this:

```
a:5:{i:0;s:39:"The configured gift could not be found.";i:1;s:4338:"#0 /home3/starar/public_html/app/code/community/Ionoi/Gift/Model/Rule/Validator.php(159): Mage::throwException('The configured ...')
#1 /home3/XXXX/public_html/app/code/community/Ionoi/Gift/Model/Rule/Validator.php(222): Ionoi_Gift_Model_Rule_Validator->_getProduct('563')
#2 /home3/XXXX/public_html/app/code/community/Ionoi/Gift/Model/Observer.php(58): Ionoi_Gift_Model_Rule_Validator->process(Object(Dhl_Account_Model_Quote_Address))
#3 /home3/XXXX/public_html/app/code/community/Ionoi/Gift/Model/Observer.php(41): Ionoi_Gift_Model_Observer->_processGiftRules(Object(Dhl_Account_Model_Quote_Address))
#4 /home3/XXXX/public_html/app/code/core/Mage/Core/Model/App.php(1338): Ionoi_Gift_Model_Observer->onQuoteAddressTotalsCollected(Object(Varien_Event_Observer))
#5 /home3/XXXX/public_html/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Ionoi_Gift_Model_Observer), 'onQuoteAddressT...', Object(Varien_Event_Observer))
#6 /home3/XXXX/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('sales_quote_add...', Array)
#7 /home3/XXXX/public_html/app/code/core/Mage/Sales/Model/Quote/Address.php(1015): Mage::dispatchEvent('sales_quote_add...', Array)
#8 /home3/XXXX/public_html/app/code/core/Mage/Sales/Model/Quote.php(1331): Mage_Sales_Model_Quote_Address->collectTotals()
#9 /home3/XXXX/public_html/app/code/core/Mage/Sales/Model/Quote.php(1907): Mage_Sales_Model_Quote->collectTotals()
#10 /home3/XXXX/public_html/app/code/core/Mage/Sales/Model/Quote.php(363): Mage_Sales_Model_Quote->_afterLoad()
#11 /home3/XXXX/public_html/app/code/core/Mage/Adminhtml/Block/Customer/Edit/Tab/View/Accordion.php(54): Mage_Sales_Model_Quote->loadByCustomer(Object(Mage_Customer_Model_Customer))
#12 /home3/XXXX/public_html/app/code/core/Mage/Core/Block/Abstract.php(293): Mage_Adminhtml_Block_Customer_Edit_Tab_View_Accordion->_prepareLayout()
#13 /home3/XXXX/public_html/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#14 /home3/XXXX/public_html/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('adminhtml/custo...', 'accordion')
#15 /home3/XXXX/public_html/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('adminhtml/custo...', 'accordion')
#16 /home3/starar/public_html/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#17 /home3/XXXX/public_html/app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#18 /home3/XXXX/public_html/app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#19 /home3/XXXX/public_html/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#20 /home3/XXXX/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#21 /home3/XXXX/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#22 /home3/XXXX/public_html/app/code/core/Mage/Adminhtml/Controller/Action.php(275): Mage_Core_Controller_Varien_Action->loadLayout(NULL, true, true)
#23 /home3/XXXX/public_html/app/code/core/Mage/Adminhtml/controllers/CustomerController.php(98): Mage_Adminhtml_Controller_Action->loadLayout()
#24 /home3/XXXX/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_CustomerController->editAction()
#25 /home3/XXXX/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#26 /home3/XXXX/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#27 /home3/XXXX/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#28 /home3/XXXX/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#29 /home3/XXXX/public_html/index.php(87): Mage::run('', 'store')
```

**Comment by giulialanzalonga23** [comment]
Hi,
is there some solution for this issue?


Thnaks
